### ISSUE TITLE
gtk4 integration 

### ISSUE THREAD

**Issue by c1ngular** [go-gst/go-gst#20]
I am trying to make an customized video player using this project with [gotk4](https://github.com/diamondburned/gotk4) , I could not make it work , tried [gotk4-gstreamer](https://github.com/OmegaRogue/gotk4-gstreamer)  as well , still no avail . 

Could you give me some directions and guidelines on this , I want to use this project to process rtsp streams and output gtk4paintablesinks , then feed it to gotk4 for final UI customization .  Here is a [discussion](https://github.com/diamondburned/gotk4/discussions/100)  as well .

Or do you happen to know any golang GUI toolkit could fit my purpose better or easier ?

Thank you .

**Comment by RSWilli** [comment]
I've not heard of gotk4-gstreamer, but I like the approach of generating the bindings automatically.

My take on this:
* I don't know if it is currently (if at all) possible to set the paintable prop on the [gtk4paintablesinks](https://gstreamer.freedesktop.org/documentation/gtk4/index.html?gi-language=c) the gst bindings do not know the [GdkPaintable](https://developer.gnome.org/gdk4/GdkPaintable.html#GdkPaintable-struct), and this is needed for the type detection in the [`SetProperty`](https://github.com/go-gst/go-glib/blob/main/glib/gobject.go#L221) function for the glib bindings. (I stumbled across this while trying to set properties with enum types)
* Alternatives:
  * use appsink and push the buffers to gotk4 somehow
  * create a new package or a subpackage (PR welcome) that binds the gst-plugin-gtk4 types somehow and provides casting of the types (probably via use of unsafe)

I do not have any experience with writing desktop applications in golang, so I cannot recommend any GUI toolkits

**Comment by c1ngular** [comment]
@RSWilli  thanks , the reason i wanna use [gtk4paintablesinks] (https://gstreamer.freedesktop.org/documentation/gtk4/index.html?gi-language=c) instead of appsink is mainly performance concern , i want to directly display(dma buf ?)  decoded video data in GPU without CPU copy . as you mentioned , i could not figure out how to expose or casting data types between different bindings , in my case ,between go-gst and gotk4 . it it possible that go-gst could expose some methods or data types for other golang bindings/projects to interact with ?

thansk again .

**Comment by RSWilli** [comment]
(nearly) all of the bindings types, structs and constants are only wrappers for the underlying C structs, types and constants. And all the [`gst-objects`](https://github.com/go-gst/go-gst/blob/main/gst/gst_object.go#L13) extend [`gobject`](https://github.com/go-gst/go-glib/blob/0abfebfabe3e1627f69a6da6e4970ef2903acc43/glib/glib.go#L462), for which `go-gst` uses the [`go-glib`](https://github.com/go-gst/go-glib) library.

This library exposes some functions such as [`Native()` and `Unsafe()`](https://github.com/go-gst/go-glib/blob/main/glib/gobject.go#L96-L108) which allows you to perform the dark magic casts you would need to cast the data types between the bindings.

But: I do not know if the [`SetProperty`](https://github.com/go-gst/go-glib/blob/main/glib/gobject.go#L208) method currently supports setting raw C pointers. (If not this would need a change to `go-glib`)

------

I would still suggest to create a separate golang module for this for several reasons:
1. the golang module cache allows for faster compilation times if the module with the bindings doesn't get modified all the time
2. you will most likely need to create a module that has both `gotk4` and `go-gst` as dependencies. I do not want to include the `gotk4` bindings in `go-gst`, since the current compilation times are awful enough (see #16)
3. from a maintainability standpoint you do not want to import the `unsafe` package in any code you want to be able to touch later

**Comment by c1ngular** [comment]
@RSWilli  thank you

**Comment by RSWilli** [comment]
@c1ngular  if you are happy with your implementation we could however move your module into the go-gst org if you want

**Comment by c1ngular** [comment]
@RSWilli  i am willing to contribute if i could come up with something , but it is a long shot since it is my first attempt with desktop GUI and media stuff , i only got the basic ideas .  thank you for your work .
