### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by onthegit** [go-gst/go-gst#40]
Hello,
pipeline with appsrc to which  flv video chunks are pushed with PushBuffer and NewBufferFromBytes() leaks memory. The memory continues to grow while the pipeline is running and stays after the pipeline has ended (EOS event followed with stateNull), and is never freed. The pipeline works and produces valid MP4 file. Gstreamer version is 1.22.0 and it is run on Debian 12.

appsrc (flv video)=>queue->flvdemux->audiotee->queue->aacparser->mp4mux->filesink 
                                                                   ->videotee->queue->h264parser->mp4mux

```
memleak-bpfcc -p 15232 -o 5000 30
```

shows continous growing allocation of memory at :

```
54947840 bytes in 13415 allocations from stack
		0x000015480133d679	g_malloc+0x19 [libglib-2.0.so.0.7400.6]
		0x0000000000000001	[unknown]
		0x00001547c40280c0	[unknown]
```

debug/pprof at NewBufferFromBytes and wrapBuffer functions.
![gst](https://github.com/go-gst/go-gst/assets/43019496/ee98eacf-10d9-4b69-8b86-40ed363bddec)

**Comment by RSWilli** [comment]
Ah interesting, I was looking at the code for a while and wondered where something like this could occur.

The created C buffers are unrefed [here](https://github.com/go-gst/go-gst/blob/main/gst/gst_buffer.go#L50) and the [wrapBuffer](https://github.com/go-gst/go-gst/blob/main/gst/gst_wrappers.go#L20) function you mention only performs a golang allocation.

The [NewBufferFromBytes function](https://github.com/go-gst/go-gst/blob/368471c8101d1dfde9d6d5ecba4a93eec73eff4c/gst/gst_buffer.go#L106) seems to correctly unref all created C objects.

Ah but I see a lonely `Ref()` call in [`PushBuffer`](https://github.com/go-gst/go-gst/blob/368471c8101d1dfde9d6d5ecba4a93eec73eff4c/gst/app/gst_app_src.go#L126) (aka no unref), that may be the source of your issue. 

I even think that there shouldn't be a `Ref()` call in the first place, since [gst_app_src_push_buffer](https://gstreamer.freedesktop.org/documentation/applib/gstappsrc.html?gi-language=c#gst_app_src_push_buffer) takes ownership of the buffer.

@onthegit could you try it out and post your feedback, or provide me with a minimal setup that I can run and profile?

**Comment by RSWilli** [comment]
@tinyzimmer what do you think?

**Comment by tinyzimmer** [comment]
> @tinyzimmer what do you think?

This isn't the first memory leak fought on those methods. The last one dates back to gstreamer 1.18. 

I'll have to look more closely to see but last I recall that buffer is just populated with a memset from the original.

**Comment by onthegit** [comment]
Hello, thanks for your replies,
I tried replacing NewBufferFromBytes with 
```
p.src.PushBuffer(gst.NewBufferFull(gst.MemoryFlagReadOnly, cp, int64(len(cp)), 0, int64(len(cp)), func() { fmt.Println('closed') }))
```go

and the memory leak is even higher.

**Comment by onthegit** [comment]
@RSWilli I tried removing Ref() and the memory still kept growing.

**Comment by onthegit** [comment]
It appears the there is memory leak in mp4mux element. Valgrind shows that there are a lot of allocations in gstreamer isomp4 library. The mp4mux element was set like this:
```go
	if err = mux.SetProperty("faststart", true); err != nil {
		return nil, errors.New("could not set property: faststart " + err.Error())
	}

	if err = mux.SetProperty("fragment-duration", uint(60)); err != nil {
		return nil, errors.New("could not set property: fragment-duration " + err.Error())
	}

	mux.SetArg("fragment-mode", "first-moov-then-finalise")
```

Once they  were removed, the leak was gone. I am still testing whether it will leak again but so far have not seen major increases in memory. Will test further.
So this might be a problem with the mp4mux element, and maybe someone with permissions at gstreamer repo can report the issue.

**Comment by RSWilli** [comment]
You could talk to the gstreamer devs on the gstreamer IRC channel.

> maybe someone with permissions at gstreamer repo can report the issue

You can create an account by yourself and get verified to report the issue, though.
