### ISSUE TITLE
Regression since v1.0.0

### ISSUE THREAD

**Issue by m1k1o** [go-gst/go-gst#98]
Getting this error:

```
# github.com/go-gst/go-gst/gst
gst/gst_debug.go:221:20: could not determine kind of name for C.gst_debug_message_get_id
```
Seems to be introdued with this commit: d0177daba60fd51d2072033275ef2fe7575369ce

Vesrion: GStreamer 1.20.3

**Comment by RSWilli** [comment]
Indeed the function was introduced in gstreamer 1.22: https://gstreamer.freedesktop.org/documentation/gstreamer/gstinfo.html?gi-language=c#gst_debug_message_get_id

Please consider upgrading your gstreamer version. By now there are two newer releases of gstreamer.: 1.22. and 1.24.

* https://gstreamer.freedesktop.org/releases/1.22/
* https://gstreamer.freedesktop.org/releases/1.24/

Since we use https://github.com/blinemedical/setup-gstreamer for its actions workflow, we build against the latest supported gstreamer version of their action, which is currently 1.22.7

**Comment by m1k1o** [comment]
Thank you very much for the fast reply. Maybe it would be benefitial to state minimum supported version of gstreamer in README / per release to avoid confusion.

**Comment by Sean-Zeo** [comment]
How do you upgrade gstreamer on ubuntu 22.04?

**Comment by m1k1o** [comment]
Firstly do not try to remove it if you do not have server, because your GUI stops working (i found out the hard way). I just [built it from source](https://gstreamer.freedesktop.org/documentation/installing/building-from-source-using-meson.html?gi-language=c) to `/opt/gstreamer` and then added it to PATH. Alternatively you can build it inside docker container and just copy it to your home system if you don't want to install build backages, but make sure that install dir stays the same.
